###########################################################
#                  SIGNER CONFIG                          #
#                                                         #
###########################################################
[settings]

# settings you might need to change:
# your individual address
KEY = "osmo15004ysvmqnqzkvt7x6s4cd53flmmvgfvqua8jr"
# a good node
RPC = "https://rpc.cosmos.directory:443/osmosis"
# account number, for offline siging. if empty a good rpc is required
ACCOUNT = ""

#### less likely youll need to change these ####
# multisig address
MULTISIG = "osmo1duj0ldp5p3qmksas35q7cq977f38a8e7chsxnw"
# where the txs are located
REPO = "doggystylez/multisig-test"
# should probably only change this if using ledger
KEYRING = "os"
# chain-id
CHAIN = "osmosis-1"
